### ISSUE TITLE
toCsvL

### ISSUE THREAD

**Issue by islandgit** [gekomad/itto-csv#2]
import com.github.gekomad.ittocsv.core.ToCsv._
		implicit val csvFormat = com.github.gekomad.ittocsv.parser.IttoCSVFormat.default.withPrintHeader(true)
		val testBean = ParquetStruct(120000000,120000000,123213,43532,123,12,3123,231,123123,312312,1,"hello",1200000000,"101","10101")
		val csvBeans: Seq[SinoiovParquetStruct] = testBean::Nil
		val csvStr = toCsvL(csvBeans)     //error
		println(csvStr)
ERROR information :
No implicits found for parameter evidence$2:Header.fieldNames[ParquetStruct]

**Comment by gekomad** [comment]
what `ParquetStruct` and `SinoiovParquetStruct` are?
